name: Publish

on:
  release:
    types: [ "published" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build & Publish
        env:
          gradle.publish.key: ${{ secrets.GRADLE_KEY }}
          gradle.publish.secret: ${{ secrets.GRADLE_SECRET }}
          repo_username: ${{ secrets.REPO_USERNAME }}
          repo_password: ${{ secrets.REPO_PASSWORD }}
        run: |
          ./gradlew publish
